version: '3.8'

services:
  ejabberd:
    image: ejabberd/ecs
    environment:
      - CTL_ON_CREATE=register admin localhost Aa1234
      - CTL_ON_START=stats registeredusers ;
                     check_password admin localhost Aa1234 ;
                     status
      # - EJABBERD_HOSTNAME=localhost
      # - EJABBERD_SQL_TYPE=pgsql
      # - EJABBERD_SQL_SERVER=postgres
      # - EJABBERD_SQL_DATABASE=ejabberd
      # - EJABBERD_SQL_USERNAME=ejabberd
      # - EJABBERD_SQL_PASSWORD=ejabberd_password
      # - MDNS_HOSTNAME= jabber.local
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
      - "5443:5443"
    volumes:
      - ./ejabberd.yml:/home/ejabberd/conf/ejabberd.yml:ro
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=ejabberd
      - POSTGRES_USER=ejabberd
      - POSTGRES_PASSWORD=ejabberd_password
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  
  ejjaberd-flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/ejabberd -user=ejabberd -password=ejabberd_password -connectRetries=60 migrate
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      - postgres

  web:
    image: nginx
    volumes:
      - ./conf/nginx:/etc/nginx/templates
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./converse.js:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    # environment:
    #   - NGINX_HOST=foobar.com
    #   - NGINX_PORT=80

volumes:
  pgdata: